# Generated by Django 5.1.6 on 2025-03-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('A', 'Perecederos'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=19, max_digits=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
